/*
 * @(#)EnumUsmUserStatus.java	1.11
 *
 * 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 * Copyright (c) 2007 Sun Microsystems, Inc. All Rights Reserved.
 * 
 * The contents of this file are subject to the terms of either the GNU General
 * Public License Version 2 only ("GPL") or the Common Development and
 * Distribution License("CDDL")(collectively, the "License"). You may not use
 * this file except in compliance with the License. You can obtain a copy of the
 * License at http://opendmk.dev.java.net/legal_notices/licenses.txt or in the 
 * LEGAL_NOTICES folder that accompanied this code. See the License for the 
 * specific language governing permissions and limitations under the License.
 * 
 * When distributing the software, include this License Header Notice in each
 * file and include the License file found at
 *     http://opendmk.dev.java.net/legal_notices/licenses.txt
 * or in the LEGAL_NOTICES folder that accompanied this code.
 * Sun designates this particular file as subject to the "Classpath" exception
 * as provided by Sun in the GPL Version 2 section of the License file that
 * accompanied this code.
 * 
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * 
 *       "Portions Copyrighted [year] [name of copyright owner]"
 * 
 * Contributor(s):
 * 
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding
 * 
 *       "[Contributor] elects to include this software in this distribution
 *        under the [CDDL or GPL Version 2] license."
 * 
 * If you don't indicate a single choice of license, a recipient has the option
 * to distribute your version of this file under either the CDDL or the GPL
 * Version 2, or to extend the choice of license to its licensees as provided
 * above. However, if you add GPL Version 2 code and therefore, elected the
 * GPL Version 2 license, then the option applies only if the new code is made
 * subject to such option by the copyright holder.
 * 
 *
 */
package com.sun.management.snmp.usm.usmmib;

//
// Generated by mibgen version 5.0 (09/06/01) when compiling SNMP-USER-BASED-SM-MIB.
//

// java imports
//
import java.io.Serializable;
import java.util.Hashtable;

// RI imports
//
import com.sun.jdmk.Enumerated;

/**
 * The class used for representing "UsmUserStatus".
 *
 *
 * @since Java DMK 5.1
 */
public class EnumUsmUserStatus extends Enumerated implements Serializable {
    private static final long serialVersionUID = -4549514339777505443L;

    protected static Hashtable intTable = new Hashtable();
    protected static Hashtable stringTable = new Hashtable();
    static  {
        intTable.put(new Integer(5), "createAndWait");
        intTable.put(new Integer(6), "destroy");
        intTable.put(new Integer(4), "createAndGo");
        intTable.put(new Integer(3), "notReady");
        intTable.put(new Integer(1), "active");
        intTable.put(new Integer(2), "notInService");
        stringTable.put("createAndWait", new Integer(5));
        stringTable.put("destroy", new Integer(6));
        stringTable.put("createAndGo", new Integer(4));
        stringTable.put("notReady", new Integer(3));
        stringTable.put("active", new Integer(1));
        stringTable.put("notInService", new Integer(2));
    }

    public EnumUsmUserStatus(int valueIndex) throws IllegalArgumentException {
        super(valueIndex);
    }

    public EnumUsmUserStatus(Integer valueIndex) throws IllegalArgumentException {
        super(valueIndex);
    }

    public EnumUsmUserStatus() throws IllegalArgumentException {
        super();
    }

    public EnumUsmUserStatus(String x) throws IllegalArgumentException {
        super(x);
    }

    protected Hashtable getIntTable() {
        return intTable ;
    }

    protected Hashtable getStringTable() {
        return stringTable ;
    }

}
