/*
 * @(#)ParserConstants.java	1.10
 *
 * 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 * Copyright (c) 2007 Sun Microsystems, Inc. All Rights Reserved.
 * 
 * The contents of this file are subject to the terms of either the GNU General
 * Public License Version 2 only ("GPL") or the Common Development and
 * Distribution License("CDDL")(collectively, the "License"). You may not use
 * this file except in compliance with the License. You can obtain a copy of the
 * License at http://opendmk.dev.java.net/legal_notices/licenses.txt or in the 
 * LEGAL_NOTICES folder that accompanied this code. See the License for the 
 * specific language governing permissions and limitations under the License.
 * 
 * When distributing the software, include this License Header Notice in each
 * file and include the License file found at
 *     http://opendmk.dev.java.net/legal_notices/licenses.txt
 * or in the LEGAL_NOTICES folder that accompanied this code.
 * Sun designates this particular file as subject to the "Classpath" exception
 * as provided by Sun in the GPL Version 2 section of the License file that
 * accompanied this code.
 * 
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * 
 *       "Portions Copyrighted [year] [name of copyright owner]"
 * 
 * Contributor(s):
 * 
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding
 * 
 *       "[Contributor] elects to include this software in this distribution
 *        under the [CDDL or GPL Version 2] license."
 * 
 * If you don't indicate a single choice of license, a recipient has the option
 * to distribute your version of this file under either the CDDL or the GPL
 * Version 2, or to extend the choice of license to its licensees as provided
 * above. However, if you add GPL Version 2 code and therefore, elected the
 * GPL Version 2 license, then the option applies only if the new code is made
 * subject to such option by the copyright holder.
 * 
 *
 */
/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package com.sun.management.snmp.uacl;

interface ParserConstants {

  int EOF = 0;
  int ACCESS = 7;
  int ACL = 8;
  int ASSIGN = 9;
  int CONTEXTNAMES = 10;
  int USERS = 11;
  int LBRACE = 12;
  int RANGE = 13;
  int RBRACE = 14;
  int RO = 15;
  int RW = 16;
  int SECURITYLEVEL = 17;
  int NOAUTHNOPRIV = 18;
  int AUTHNOPRIV = 19;
  int AUTHPRIV = 20;
  int INTEGER_LITERAL = 21;
  int DECIMAL_LITERAL = 22;
  int HEX_LITERAL = 23;
  int OCTAL_LITERAL = 24;
  int IDENTIFIER = 25;
  int LETTER = 26;
  int SEPARATOR = 27;
  int DIGIT = 28;
  int ANY_USER = 29;
  int CSTRING = 30;
  int COMMA = 31;
  int DOT = 32;
  int MARK = 33;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"access\"",
    "\"acl\"",
    "\"=\"",
    "\"context-names\"",
    "\"users\"",
    "\"{\"",
    "\"-\"",
    "\"}\"",
    "\"read-only\"",
    "\"read-write\"",
    "\"security-level\"",
    "\"noAuthNoPriv\"",
    "\"authNoPriv\"",
    "\"authPriv\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SEPARATOR>",
    "<DIGIT>",
    "<ANY_USER>",
    "<CSTRING>",
    "\",\"",
    "\".\"",
    "\"!\"",
  };

}
