/*
 * @(#)ParserTreeConstants.java	4.15
 *
 * 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 * Copyright (c) 2007 Sun Microsystems, Inc. All Rights Reserved.
 * 
 * The contents of this file are subject to the terms of either the GNU General
 * Public License Version 2 only ("GPL") or the Common Development and
 * Distribution License("CDDL")(collectively, the "License"). You may not use
 * this file except in compliance with the License. You can obtain a copy of the
 * License at http://opendmk.dev.java.net/legal_notices/licenses.txt or in the 
 * LEGAL_NOTICES folder that accompanied this code. See the License for the 
 * specific language governing permissions and limitations under the License.
 * 
 * When distributing the software, include this License Header Notice in each
 * file and include the License file found at
 *     http://opendmk.dev.java.net/legal_notices/licenses.txt
 * or in the LEGAL_NOTICES folder that accompanied this code.
 * Sun designates this particular file as subject to the "Classpath" exception
 * as provided by Sun in the GPL Version 2 section of the License file that
 * accompanied this code.
 * 
 * If applicable, add the following below the License Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * 
 *       "Portions Copyrighted [year] [name of copyright owner]"
 * 
 * Contributor(s):
 * 
 * If you wish your version of this file to be governed by only the CDDL or
 * only the GPL Version 2, indicate your decision by adding
 * 
 *       "[Contributor] elects to include this software in this distribution
 *        under the [CDDL or GPL Version 2] license."
 * 
 * If you don't indicate a single choice of license, a recipient has the option
 * to distribute your version of this file under either the CDDL or the GPL
 * Version 2, or to extend the choice of license to its licensees as provided
 * above. However, if you add GPL Version 2 code and therefore, elected the
 * GPL Version 2 license, then the option applies only if the new code is made
 * subject to such option by the copyright holder.
 * 
 *
 */
/* Generated By:JJTree: Do not edit this line. ParserTreeConstants.java */

package com.sun.management.snmp.IPAcl;

interface ParserTreeConstants
{
  public int JJTSECURITYDEFS = 0;
  public int JJTACLBLOCK = 1;
  public int JJTACLITEM = 2;
  public int JJTCOMMUNITIES = 3;
  public int JJTCOMMUNITY = 4;
  public int JJTACCESS = 5;
  public int JJTMANAGERS = 6;
  public int JJTHOST = 7;
  public int JJTHOSTNAME = 8;
  public int JJTIPADDRESS = 9;
  public int JJTIPV6ADDRESS = 10;
  public int JJTIPMASK = 11;
  public int JJTNETMASK = 12;
  public int JJTNETMASKV6 = 13;
  public int JJTTRAPBLOCK = 14;
  public int JJTTRAPITEM = 15;
  public int JJTTRAPCOMMUNITY = 16;
  public int JJTTRAPINTERESTEDHOST = 17;
  public int JJTHOSTTRAP = 18;
  public int JJTENTERPRISE = 19;
  public int JJTTRAPNUM = 20;
  public int JJTINFORMBLOCK = 21;
  public int JJTINFORMITEM = 22;
  public int JJTINFORMCOMMUNITY = 23;
  public int JJTINFORMINTERESTEDHOST = 24;
  public int JJTHOSTINFORM = 25;


  public String[] jjtNodeName = {
    "SecurityDefs",
    "AclBlock",
    "AclItem",
    "Communities",
    "Community",
    "Access",
    "Managers",
    "Host",
    "HostName",
    "IpAddress",
    "IpV6Address",
    "IpMask",
    "NetMask",
    "NetMaskV6",
    "TrapBlock",
    "TrapItem",
    "TrapCommunity",
    "TrapInterestedHost",
    "HostTrap",
    "Enterprise",
    "TrapNum",
    "InformBlock",
    "InformItem",
    "InformCommunity",
    "InformInterestedHost",
    "HostInform",
  };
}
